<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="3" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-05-24T13:13:48Z" name="AccountsFunctionality" finished-at="2021-05-24T13:14:24Z" duration-ms="35891">
    <groups>
    </groups>
    <test started-at="2021-05-24T13:13:48Z" name="Accounts Test on chrome" finished-at="2021-05-24T13:14:24Z" duration-ms="35891">
      <class name="testcases.VerifyAccountsModule">
        <test-method is-config="true" signature="setBrowser(java.lang.String, org.testng.ITestContext)[pri:0, instance:testcases.VerifyAccountsModule@6337c201]" started-at="2021-05-24T07:13:48Z" name="setBrowser" finished-at="2021-05-24T07:13:48Z" duration-ms="13" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@3ad4a7d6]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setBrowser -->
        <test-method is-config="true" signature="CreateReport(java.lang.reflect.Method)[pri:0, instance:testcases.VerifyAccountsModule@6337c201]" started-at="2021-05-24T07:13:48Z" name="CreateReport" finished-at="2021-05-24T07:13:48Z" duration-ms="10" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void testcases.VerifyAccountsModule.TC10_CreateAccount(java.lang.reflect.Method) throws java.io.IOException,java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateReport -->
        <test-method signature="TC10_CreateAccount(java.lang.reflect.Method)[pri:0, instance:testcases.VerifyAccountsModule@6337c201]" started-at="2021-05-24T07:13:48Z" name="TC10_CreateAccount" finished-at="2021-05-24T07:14:02Z" duration-ms="14173" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void testcases.VerifyAccountsModule.TC10_CreateAccount(java.lang.reflect.Method) throws java.io.IOException,java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC10_CreateAccount -->
        <test-method is-config="true" signature="CloseDriver()[pri:0, instance:testcases.VerifyAccountsModule@6337c201]" started-at="2021-05-24T07:14:02Z" name="CloseDriver" finished-at="2021-05-24T07:14:09Z" duration-ms="7201" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseDriver -->
        <test-method is-config="true" signature="CreateReport(java.lang.reflect.Method)[pri:0, instance:testcases.VerifyAccountsModule@6337c201]" started-at="2021-05-24T07:14:09Z" name="CreateReport" finished-at="2021-05-24T07:14:09Z" duration-ms="0" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void testcases.VerifyAccountsModule.TC12_Editview(java.lang.reflect.Method) throws java.io.IOException,java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateReport -->
        <test-method signature="TC12_Editview(java.lang.reflect.Method)[pri:0, instance:testcases.VerifyAccountsModule@6337c201]" started-at="2021-05-24T07:14:09Z" name="TC12_Editview" finished-at="2021-05-24T07:14:23Z" duration-ms="14053" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void testcases.VerifyAccountsModule.TC12_Editview(java.lang.reflect.Method) throws java.io.IOException,java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <exception class="org.openqa.selenium.NoSuchElementException">
            <message>
              <![CDATA[Cannot locate element with text: NirmalaShanmugamani
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-55TGAJ2', ip: '192.168.0.25', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '15.0.1'
Driver info: driver.version: unknown]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.NoSuchElementException: Cannot locate element with text: NirmalaShanmugamani
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-55TGAJ2', ip: '192.168.0.25', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '15.0.1'
Driver info: driver.version: unknown
	at org.openqa.selenium.support.ui.Select.selectByVisibleText(Select.java:147)
	at base.BaseTest.SelectByText(BaseTest.java:171)
	at testcases.VerifyAccountsModule.TC12_Editview(VerifyAccountsModule.java:113)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.NoSuchElementException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC12_Editview -->
        <test-method is-config="true" signature="CloseDriver()[pri:0, instance:testcases.VerifyAccountsModule@6337c201]" started-at="2021-05-24T07:14:24Z" name="CloseDriver" finished-at="2021-05-24T07:14:24Z" duration-ms="0" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [https://abccom359-dev-ed.my.salesforce.com/setup/forcecomHomepage.apexp?setupid=ForceCom] but found [https://abccom359-dev-ed--c.documentforce.com/secur/contentDoor?startURL=https%3A%2F%2Fabccom359-dev-ed.my.salesforce.com%2Fsetup%2FforcecomHomepage.apexp%3Fsetupid%3DForceCom&sid=00D5e000000J7Y4%21AQkAQDBgXXsmukRAvsqDy_ARHCwuvnnK82sgmDifY024M2Ca5XlGdJaZvWrKGcTUGC4.wdpdII00DpWceXtd2urjM.Dy3Jjd&skipRedirect=1&lm=eyJlbmMiOiJBMjU2R0NNIiwiYXVkIjoiMDBENWUwMDAwMDBKN1k0Iiwia2lkIjoie1widFwiOlwiMDBENWUwMDAwMDBKN1k0XCIsXCJ2XCI6XCIwMkc1ZTAwMDAwMFBuU2tcIixcImFcIjpcImNvbnRlbnRkb29ydXNlcnRyYW5zaWVudGtleWVuY3J5cHRcIixcInVcIjpcIjAwNTVlMDAwMDAwcVhzbVwifSIsImNyaXQiOlsiaWF0Il0sImlhdCI6MTYyMTg2MjA1MjcyMSwiZXhwIjowfQ%3D%3D..iqojOJ7grTZPXflx.pagRrD-6Q0k7EFB2wtNpJw%3D%3D.Iqa_MMWmrLgl2iBFi3Ioyg%3D%3D]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [https://abccom359-dev-ed.my.salesforce.com/setup/forcecomHomepage.apexp?setupid=ForceCom] but found [https://abccom359-dev-ed--c.documentforce.com/secur/contentDoor?startURL=https%3A%2F%2Fabccom359-dev-ed.my.salesforce.com%2Fsetup%2FforcecomHomepage.apexp%3Fsetupid%3DForceCom&sid=00D5e000000J7Y4%21AQkAQDBgXXsmukRAvsqDy_ARHCwuvnnK82sgmDifY024M2Ca5XlGdJaZvWrKGcTUGC4.wdpdII00DpWceXtd2urjM.Dy3Jjd&skipRedirect=1&lm=eyJlbmMiOiJBMjU2R0NNIiwiYXVkIjoiMDBENWUwMDAwMDBKN1k0Iiwia2lkIjoie1widFwiOlwiMDBENWUwMDAwMDBKN1k0XCIsXCJ2XCI6XCIwMkc1ZTAwMDAwMFBuU2tcIixcImFcIjpcImNvbnRlbnRkb29ydXNlcnRyYW5zaWVudGtleWVuY3J5cHRcIixcInVcIjpcIjAwNTVlMDAwMDAwcVhzbVwifSIsImNyaXQiOlsiaWF0Il0sImlhdCI6MTYyMTg2MjA1MjcyMSwiZXhwIjowfQ%3D%3D..iqojOJ7grTZPXflx.pagRrD-6Q0k7EFB2wtNpJw%3D%3D.Iqa_MMWmrLgl2iBFi3Ioyg%3D%3D]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at testcases.VerifyAccountsModule.CloseDriver(VerifyAccountsModule.java:40)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:712)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseDriver -->
      </class> <!-- testcases.VerifyAccountsModule -->
    </test> <!-- Accounts Test on chrome -->
  </suite> <!-- AccountsFunctionality -->
</testng-results>
