<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite ignored="0" hostname="DESKTOP-55TGAJ2" failures="1" tests="2" name="testcases.VerifyLoginFunctionality_2" time="20.171" errors="0" timestamp="22 May 2021 13:42:16 GMT" skipped="0">
  <testcase classname="testcases.VerifyLoginFunctionality_2" name="VerifyLoginToSalseForce_02" time="13.186">
    <failure message="The following asserts failed:
	expected [https://abccom359-dev-ed.my.salesforce.com/setup/forcecomHomepage.apexp?setupid=ForceCom] but found [https://abccom359-dev-ed--c.documentforce.com/secur/contentDoor?startURL=https%3A%2F%2Fabccom359-dev-ed.my.salesforce.com%2Fsetup%2FforcecomHomepage.apexp%3Fsetupid%3DForceCom&amp;sid=00D5e000000J7Y4%21AQkAQC20kfZFqy.BmfwFlA71wyT0_KoMuD9GVuqq9VA_qkqmfB.mS2XKCHeOAS_WCTbnhBPevUQEcy7kLg1dvTmN9hCDuxKW&amp;skipRedirect=1&amp;lm=eyJlbmMiOiJBMjU2R0NNIiwiYXVkIjoiMDBENWUwMDAwMDBKN1k0Iiwia2lkIjoie1widFwiOlwiMDBENWUwMDAwMDBKN1k0XCIsXCJ2XCI6XCIwMkc1ZTAwMDAwMFBuU2tcIixcImFcIjpcImNvbnRlbnRkb29ydXNlcnRyYW5zaWVudGtleWVuY3J5cHRcIixcInVcIjpcIjAwNTVlMDAwMDAwcVhzbVwifSIsImNyaXQiOlsiaWF0Il0sImlhdCI6MTYyMTY5MDkyNDk0NCwiZXhwIjowfQ%3D%3D..R15nLYGwDDH_eL1N.QrqM7FwIqUv7owj2KhprmA%3D%3D.d8fIT_l6o7Oa7yuFxoRarA%3D%3D]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [https://abccom359-dev-ed.my.salesforce.com/setup/forcecomHomepage.apexp?setupid=ForceCom] but found [https://abccom359-dev-ed--c.documentforce.com/secur/contentDoor?startURL=https%3A%2F%2Fabccom359-dev-ed.my.salesforce.com%2Fsetup%2FforcecomHomepage.apexp%3Fsetupid%3DForceCom&sid=00D5e000000J7Y4%21AQkAQC20kfZFqy.BmfwFlA71wyT0_KoMuD9GVuqq9VA_qkqmfB.mS2XKCHeOAS_WCTbnhBPevUQEcy7kLg1dvTmN9hCDuxKW&skipRedirect=1&lm=eyJlbmMiOiJBMjU2R0NNIiwiYXVkIjoiMDBENWUwMDAwMDBKN1k0Iiwia2lkIjoie1widFwiOlwiMDBENWUwMDAwMDBKN1k0XCIsXCJ2XCI6XCIwMkc1ZTAwMDAwMFBuU2tcIixcImFcIjpcImNvbnRlbnRkb29ydXNlcnRyYW5zaWVudGtleWVuY3J5cHRcIixcInVcIjpcIjAwNTVlMDAwMDAwcVhzbVwifSIsImNyaXQiOlsiaWF0Il0sImlhdCI6MTYyMTY5MDkyNDk0NCwiZXhwIjowfQ%3D%3D..R15nLYGwDDH_eL1N.QrqM7FwIqUv7owj2KhprmA%3D%3D.d8fIT_l6o7Oa7yuFxoRarA%3D%3D]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at testcases.VerifyLoginFunctionality_2.VerifyLoginToSalseForce_02(VerifyLoginFunctionality_2.java:120)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- VerifyLoginToSalseForce_02 -->
  <testcase classname="testcases.VerifyLoginFunctionality_2" name="VerifyLoginErrorMessage_01" time="6.985"/>
</testsuite> <!-- testcases.VerifyLoginFunctionality_2 -->
